var data = [
 {
   "Entry Number": 1,
   "Last Name": "Conlon",
   "Middle": "Louise",
   "First": "Siena",
   "Age": 5,
   "Location": "FWMSH",
   "Email": "nlcampa@gmail.com",
   "School": "Keller-Harvel",
   "Grade Level": "Elementary",
   "Teacher": "Mrs. Wimberley",
   "Teacher's Email": "becky.wimberley@kellerisd.net",
   "Art School": "",
   "Art Teacher": "",
   "Art Teacher's Email": "",
   "Individual Entry": "Individual Entry",
   "Individual Age Division": "5-6 years old",
   "Short Answer": "",
   "Classroom Entry": "",
   "Classroom Division": "",
   "Entry Title": "\"Flower Texas\"",
   "For 3D ONLY - Description of entry": "",
   "Please Check One": [
      "Disagree",
      "Signatures Included"
   ],
   "Browser": "Chrome 94.0.4606.81 / Windows"
},
 {
   "Entry Number": 2,
   "Last Name": "Sturman",
   "Middle": "",
   "First": "Ella",
   "Age": 10,
   "Location": "FWMSH",
   "Email": "jonsturman@hotmail.com",
   "School": "Annie Purl",
   "Grade Level": "Elementary",
   "Teacher": "",
   "Teacher's Email": "",
   "Art School": "",
   "Art Teacher": "",
   "Art Teacher's Email": "",
   "Individual Entry": "Individual Entry",
   "Individual Age Division": "9-11 years old",
   "Short Answer": "",
   "Classroom Entry": "",
   "Classroom Division": "",
   "Entry Title": "\"Abstract Rooster\" ",
   "For 3D ONLY - Description of entry": "",
   "Please Check One": [
      "Disagree",
      "Signatures Included"
   ],
   "Browser": "Chrome 94.0.4606.81 / Windows"
},
 {
   "Entry Number": 3,
   "Last Name": "Crum",
   "Middle": "",
   "First": "Caya",
   "Age": 16,
   "Location": "Cowgirl",
   "Email": "caya@brazosfilms.com",
   "School": "Paschal High School",
   "Grade Level": "High",
   "Teacher": "Cavan Crane",
   "Teacher's Email": "cavan.crane@fwisd.org",
   "Art School": "",
   "Art Teacher": "",
   "Art Teacher's Email": "",
   "Individual Entry": "Individual Entry",
   "Individual Age Division": "High School 3-D",
   "Short Answer": "",
   "Classroom Entry": "",
   "Classroom Division": "",
   "Entry Title": "\"Welcome to Cowtown\" ",
   "For 3D ONLY - Description of entry": "Triptych - watercolor, wood, golf leaf, window",
   "Please Check One": [
      "Agree",
      "Signatures Included"
   ],
   "Browser": "Chrome 94.0.4606.81 / Windows"
},
 {
   "Entry Number": 4,
   "Last Name": "West",
   "Middle": "Rose",
   "First": "Sophie",
   "Age": 5,
   "Location": "FWMSH",
   "Email": "marywest0413@gmail.com",
   "School": "Homeschool",
   "Grade Level": "Elementary",
   "Teacher": "",
   "Teacher's Email": "",
   "Art School": "",
   "Art Teacher": "",
   "Art Teacher's Email": "",
   "Individual Entry": "Individual Entry",
   "Individual Age Division": "5-6 years old",
   "Short Answer": "",
   "Classroom Entry": "",
   "Classroom Division": "",
   "Entry Title": "\"A Texas Rainbow\"",
   "For 3D ONLY - Description of entry": "",
   "Please Check One": [
      "Agree",
      "Signatures Included"
   ],
   "Browser": "Chrome 94.0.4606.81 / Windows"
},
 {
   "Entry Number": 5,
   "Last Name": "West",
   "Middle": "Mackenzie",
   "First": "Ruth",
   "Age": 7,
   "Location": "FWMSH",
   "Email": "marywest0413@gmail.com",
   "School": "Homeschool",
   "Grade Level": "Elementary",
   "Teacher": "",
   "Teacher's Email": "",
   "Art School": "",
   "Art Teacher": "",
   "Art Teacher's Email": "",
   "Individual Entry": "Individual Entry",
   "Individual Age Division": "7-8 years old",
   "Short Answer": "",
   "Classroom Entry": "",
   "Classroom Division": "",
   "Entry Title": "\"Texas Sunset Beauty\"",
   "For 3D ONLY - Description of entry": "",
   "Please Check One": [
      "Agree",
      "Signatures Included"
   ],
   "Browser": "Chrome 94.0.4606.81 / Windows"
},
 {
   "Entry Number": 6,
   "Last Name": "Sipes",
   "Middle": "F",
   "First": "Aubrey",
   "Age": 11,
   "Location": "FWMSH",
   "Email": "jaime_faith@sbcglobal.net",
   "School": "Garner Elementary ",
   "Grade Level": "Middle",
   "Teacher": "Amy Glover",
   "Teacher's Email": "aglover@garnerisd.net",
   "Art School": "",
   "Art Teacher": "",
   "Art Teacher's Email": "",
   "Individual Entry": "Individual Entry",
   "Individual Age Division": "9-11 years old",
   "Short Answer": "",
   "Classroom Entry": "",
   "Classroom Division": "",
   "Entry Title": "\"Texas Bluebonnet Country\"",
   "For 3D ONLY - Description of entry": "",
   "Please Check One": [
      "Disagree",
      "Signatures Included"
   ],
   "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 7,
  "Last Name": "Doe",
  "Middle": "Louise",
  "First": "Jane",
  "Age": 5,
  "Location": "FWMSH",
  "Email": "nlcampa@gmail.com",
  "School": "Keller-Harvel",
  "Grade Level": "Elementary",
  "Teacher": "Mrs. Wimberley",
  "Teacher's Email": "becky.wimberley@kellerisd.net",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "5-6 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Flower Texas\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Disagree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 8,
  "Last Name": "Perez",
  "Middle": "",
  "First": "Jose",
  "Age": 10,
  "Location": "FWMSH",
  "Email": "jonsturman@hotmail.com",
  "School": "Annie Purl",
  "Grade Level": "Elementary",
  "Teacher": "",
  "Teacher's Email": "",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "9-11 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Abstract Rooster\" ",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Disagree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 9,
  "Last Name": "Smith",
  "Middle": "",
  "First": "John",
  "Age": 16,
  "Location": "Cowgirl",
  "Email": "caya@brazosfilms.com",
  "School": "Paschal High School",
  "Grade Level": "High",
  "Teacher": "Cavan Crane",
  "Teacher's Email": "cavan.crane@fwisd.org",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "High School 3-D",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Welcome to Cowtown\" ",
  "For 3D ONLY - Description of entry": "Triptych - watercolor, wood, golf leaf, window",
  "Please Check One": [
     "Agree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 10,
  "Last Name": "O'Callahan",
  "Middle": "Rose",
  "First": "Donna",
  "Age": 5,
  "Location": "FWMSH",
  "Email": "marywest0413@gmail.com",
  "School": "Homeschool",
  "Grade Level": "Elementary",
  "Teacher": "",
  "Teacher's Email": "",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "5-6 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"A Texas Rainbow\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Agree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 11,
  "Last Name": "Jackson",
  "Middle": "Mackenzie",
  "First": "J'Mar",
  "Age": 7,
  "Location": "FWMSH",
  "Email": "marywest0413@gmail.com",
  "School": "Homeschool",
  "Grade Level": "Elementary",
  "Teacher": "",
  "Teacher's Email": "",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "7-8 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Texas Sunset Beauty\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Agree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 12,
  "Last Name": "Jacoby",
  "Middle": "F",
  "First": "Upton",
  "Age": 11,
  "Location": "FWMSH",
  "Email": "jaime_faith@sbcglobal.net",
  "School": "Garner Elementary ",
  "Grade Level": "Middle",
  "Teacher": "Amy Glover",
  "Teacher's Email": "aglover@garnerisd.net",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "9-11 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Texas Bluebonnet Country\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Disagree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 13,
  "Last Name": "Du",
  "Middle": "",
  "First": "Lin",
  "Age": 5,
  "Location": "FWMSH",
  "Email": "nlcampa@gmail.com",
  "School": "Keller-Harvel",
  "Grade Level": "Elementary",
  "Teacher": "Mrs. Wimberley",
  "Teacher's Email": "becky.wimberley@kellerisd.net",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "5-6 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Flower Texas\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Disagree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 14,
  "Last Name": "Bankman",
  "Middle": "",
  "First": "Alex",
  "Age": 10,
  "Location": "FWMSH",
  "Email": "jonsturman@hotmail.com",
  "School": "Annie Purl",
  "Grade Level": "Elementary",
  "Teacher": "",
  "Teacher's Email": "",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "9-11 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Abstract Rooster\" ",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Disagree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 15,
  "Last Name": "Lopez",
  "Middle": "",
  "First": "Jesus",
  "Age": 16,
  "Location": "Cowgirl",
  "Email": "caya@brazosfilms.com",
  "School": "Paschal High School",
  "Grade Level": "High",
  "Teacher": "Cavan Crane",
  "Teacher's Email": "cavan.crane@fwisd.org",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "High School 3-D",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Welcome to Cowtown\" ",
  "For 3D ONLY - Description of entry": "Triptych - watercolor, wood, golf leaf, window",
  "Please Check One": [
     "Agree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 16,
  "Last Name": "Jackson",
  "Middle": "Rose",
  "First": "John",
  "Age": 5,
  "Location": "FWMSH",
  "Email": "marywest0413@gmail.com",
  "School": "Homeschool",
  "Grade Level": "Elementary",
  "Teacher": "",
  "Teacher's Email": "",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "5-6 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"A Texas Rainbow\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Agree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 17,
  "Last Name": "Smith",
  "Middle": "Mackenzie",
  "First": "Theodore",
  "Age": 7,
  "Location": "FWMSH",
  "Email": "marywest0413@gmail.com",
  "School": "Homeschool",
  "Grade Level": "Elementary",
  "Teacher": "",
  "Teacher's Email": "",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "7-8 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Texas Sunset Beauty\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Agree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
  "Entry Number": 18,
  "Last Name": "Hunt",
  "Middle": "F",
  "First": "Archie",
  "Age": 11,
  "Location": "FWMSH",
  "Email": "jaime_faith@sbcglobal.net",
  "School": "Garner Elementary ",
  "Grade Level": "Middle",
  "Teacher": "Amy Glover",
  "Teacher's Email": "aglover@garnerisd.net",
  "Art School": "",
  "Art Teacher": "",
  "Art Teacher's Email": "",
  "Individual Entry": "Individual Entry",
  "Individual Age Division": "9-11 years old",
  "Short Answer": "",
  "Classroom Entry": "",
  "Classroom Division": "",
  "Entry Title": "\"Texas Bluebonnet Country\"",
  "For 3D ONLY - Description of entry": "",
  "Please Check One": [
     "Disagree",
     "Signatures Included"
  ],
  "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
 "Entry Number": 19,
 "Last Name": "Samson",
 "Middle": "Louise",
 "First": "Jalen",
 "Age": 5,
 "Location": "FWMSH",
 "Email": "nlcampa@gmail.com",
 "School": "Keller-Harvel",
 "Grade Level": "Elementary",
 "Teacher": "Mrs. Wimberley",
 "Teacher's Email": "becky.wimberley@kellerisd.net",
 "Art School": "",
 "Art Teacher": "",
 "Art Teacher's Email": "",
 "Individual Entry": "Individual Entry",
 "Individual Age Division": "5-6 years old",
 "Short Answer": "",
 "Classroom Entry": "",
 "Classroom Division": "",
 "Entry Title": "\"Flower Texas\"",
 "For 3D ONLY - Description of entry": "",
 "Please Check One": [
    "Disagree",
    "Signatures Included"
 ],
 "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
 "Entry Number": 20,
 "Last Name": "Ruth",
 "Middle": "",
 "First": "Joyce",
 "Age": 10,
 "Location": "FWMSH",
 "Email": "jonsturman@hotmail.com",
 "School": "Annie Purl",
 "Grade Level": "Elementary",
 "Teacher": "",
 "Teacher's Email": "",
 "Art School": "",
 "Art Teacher": "",
 "Art Teacher's Email": "",
 "Individual Entry": "Individual Entry",
 "Individual Age Division": "9-11 years old",
 "Short Answer": "",
 "Classroom Entry": "",
 "Classroom Division": "",
 "Entry Title": "\"Abstract Rooster\" ",
 "For 3D ONLY - Description of entry": "",
 "Please Check One": [
    "Disagree",
    "Signatures Included"
 ],
 "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
 "Entry Number": 21,
 "Last Name": "Gooding",
 "Middle": "",
 "First": "Sara",
 "Age": 16,
 "Location": "Cowgirl",
 "Email": "caya@brazosfilms.com",
 "School": "Paschal High School",
 "Grade Level": "High",
 "Teacher": "Cavan Crane",
 "Teacher's Email": "cavan.crane@fwisd.org",
 "Art School": "",
 "Art Teacher": "",
 "Art Teacher's Email": "",
 "Individual Entry": "Individual Entry",
 "Individual Age Division": "High School 3-D",
 "Short Answer": "",
 "Classroom Entry": "",
 "Classroom Division": "",
 "Entry Title": "\"Welcome to Cowtown\" ",
 "For 3D ONLY - Description of entry": "Triptych - watercolor, wood, golf leaf, window",
 "Please Check One": [
    "Agree",
    "Signatures Included"
 ],
 "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
 "Entry Number": 22,
 "Last Name": "Hermanez",
 "Middle": "Rose",
 "First": "Javier",
 "Age": 5,
 "Location": "FWMSH",
 "Email": "marywest0413@gmail.com",
 "School": "Homeschool",
 "Grade Level": "Elementary",
 "Teacher": "",
 "Teacher's Email": "",
 "Art School": "",
 "Art Teacher": "",
 "Art Teacher's Email": "",
 "Individual Entry": "Individual Entry",
 "Individual Age Division": "5-6 years old",
 "Short Answer": "",
 "Classroom Entry": "",
 "Classroom Division": "",
 "Entry Title": "\"A Texas Rainbow\"",
 "For 3D ONLY - Description of entry": "",
 "Please Check One": [
    "Agree",
    "Signatures Included"
 ],
 "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
 "Entry Number": 23,
 "Last Name": "James",
 "Middle": "Mackenzie",
 "First": "La'sheika",
 "Age": 7,
 "Location": "FWMSH",
 "Email": "marywest0413@gmail.com",
 "School": "Homeschool",
 "Grade Level": "Elementary",
 "Teacher": "",
 "Teacher's Email": "",
 "Art School": "",
 "Art Teacher": "",
 "Art Teacher's Email": "",
 "Individual Entry": "Individual Entry",
 "Individual Age Division": "7-8 years old",
 "Short Answer": "",
 "Classroom Entry": "",
 "Classroom Division": "",
 "Entry Title": "\"Texas Sunset Beauty\"",
 "For 3D ONLY - Description of entry": "",
 "Please Check One": [
    "Agree",
    "Signatures Included"
 ],
 "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
 "Entry Number": 24,
 "Last Name": "Manze",
 "Middle": "F",
 "First": "Jonnie",
 "Age": 11,
 "Location": "FWMSH",
 "Email": "jaime_faith@sbcglobal.net",
 "School": "Garner Elementary ",
 "Grade Level": "Middle",
 "Teacher": "Amy Glover",
 "Teacher's Email": "aglover@garnerisd.net",
 "Art School": "",
 "Art Teacher": "",
 "Art Teacher's Email": "",
 "Individual Entry": "Individual Entry",
 "Individual Age Division": "9-11 years old",
 "Short Answer": "",
 "Classroom Entry": "",
 "Classroom Division": "",
 "Entry Title": "\"Texas Bluebonnet Country\"",
 "For 3D ONLY - Description of entry": "",
 "Please Check One": [
    "Disagree",
    "Signatures Included"
 ],
 "Browser": "Chrome 94.0.4606.81 / Windows"
},
{
 "Entry Number": 25,
 "Last Name": "Montague",
 "Middle": "F",
 "First": "Katherine",
 "Age": 11,
 "Location": "FWMSH",
 "Email": "jaime_faith@sbcglobal.net",
 "School": "Garner Elementary ",
 "Grade Level": "Middle",
 "Teacher": "Amy Glover",
 "Teacher's Email": "aglover@garnerisd.net",
 "Art School": "",
 "Art Teacher": "",
 "Art Teacher's Email": "",
 "Individual Entry": "Individual Entry",
 "Individual Age Division": "9-11 years old",
 "Short Answer": "",
 "Classroom Entry": "",
 "Classroom Division": "",
 "Entry Title": "\"Texas Bluebonnet Country\"",
 "For 3D ONLY - Description of entry": "",
 "Please Check One": [
    "Disagree",
    "Signatures Included"
 ],
 "Browser": "Chrome 94.0.4606.81 / Windows"
}
]
